### ISSUE TITLE
ProductSearcher does not work if ProductRepository is decorated

### ISSUE THREAD

**Issue by stefanbwt** [findologic/plugin-shopware-6#320]
Parameter 2 of FINDOLOGIC\FinSearch\Export\Search\ProductSearcher should be of type EntityRepositoryInterface.

Error ocours on product export if Plugin PickwareErpStarter is installed with findologic Plugin 3.1.1

**Comment by TobiasGraml11** [comment]
Hello @stefanbwt,

The `EntityRepositoryInterface` is deprecated right now, so we are using the suggested replacement, which is just `EntityRepository`.

![image](https://user-images.githubusercontent.com/51320851/192705273-23a23522-06f3-4f71-aec8-1f72bd56cb34.png)

**Comment by stefanbwt** [comment]
Hello,

Ok makes sense, but causes an error with activated PickwareErp Plugin during product export...

Thanks for Info
Stefan Bahn



Von: Tobias Graml ***@***.***>
Gesendet: Mittwoch, 28. September 2022 08:36
An: findologic/plugin-shopware-6 ***@***.***>
Cc: Bahn Stefan ***@***.***>; Mention ***@***.***>
Betreff: Re: [findologic/plugin-shopware-6] ProductSearcher does not work if ProductRepository is decorated (Issue #320)


Hello @stefanbwt<https://github.com/stefanbwt>,

The EntityRepositoryInterface is deprecated right now, so we are using the suggested replacement, which is just EntityRepository.

[image]<https://user-images.githubusercontent.com/51320851/192705273-23a23522-06f3-4f71-aec8-1f72bd56cb34.png>

**Comment by TobiasGraml11** [comment]
Hello @stefanbwt,

The plugin seems to extend the service for the product repository and their class is probably using `EntityRepositoryInterface`.
I don't have access to their code, but the best would be, if they could change that in their plugin, as it will be needed for v6.5 anyway.

Cheers,
Tobias
